### ISSUE TITLE
Can't get name of workspace volume

### ISSUE THREAD

**Issue by jarkenau** [naturerobots/HSOS-SEP-PlantMap-2022#210]
Currently, we have three Docker volumes for our setup:

```
DRIVER    VOLUME NAME
local     1c285a04d522f7699a5d162d3441ed10ba208df51098e4a43d86d7778e6c3c0e
local     hsos-sep-plantmap-2022_devcontainer_postgres-data
local     vscode
```
The first volume ist the bind mount for the workspace from the docker-compose:

```
...
plant-map-dev:
    image: ghcr.io/naturerobots/plant-map-digital-logbook:latest
    volumes:
      - ..:/workdir:cached
    depends_on:
      - postgres
      - rabbitmq
 ....
```

Since it has a random name I can't create a docker clean up script, to delete all docker files regarding this project. I didn't find a way to use named volumes or labels, I'm not even sure if it's possible https://stackoverflow.com/questions/51121048/mounting-a-directory-to-a-named-volume-in-docker.

@Anafabula @mklpiening do you guys have any idea for another approach?
